name: flutter_habbit_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.2.1
  sqflite_common_ffi: ^2.3.4+3
  path_provider: ^2.0.15
  shared_preferences: ^2.1.0
  http: ^1.0.0
  flutter_animate: ^4.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.0.0
  confetti: ^0.7.0
  flutter_local_notifications: ^14.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
